### ISSUE TITLE
do not commit wheel and tar.gz

### ISSUE THREAD

**Issue by srevinsaju** [kewbish/Justin#11]
binary wheels are not supposed to be in GitHub repos, rather it should be in release assets. the size of the repo has increased, and will affect future clones. This will be a packaged object in `.git` forever*, unless you use a [git cleaner](https://google.com/search?q=git+cleaner).

**Comment by kewbish** [comment]
🤦‍♀- forgot to add to .gitignore before I pushed.

It's only a couple hundred kilobytes, it should be fine. Will add in a future commit.
