### ISSUE TITLE
information provided in Readme is partially wrong

### ISSUE THREAD

**Issue by srevinsaju** [kewbish/Justin#12]
In https://github.com/kewbish/Justin#wrench-setup
it is said that the file would be founf in /usr/..../... on Linux and Mac.
However, this is incorrect.

It can be anywhere in 
```
/usr/local/lib/python3/site-packages
/usr/local/lib/python3/dist-packages
/usr/local/lib/python3.7/dist-packages
/usr/local/lib/python3.7/site-packages
/usr/lib/python3/site-packages
/usr/lib/python3.7/site-packages
/usr/lib/python3.8/site-packages
/usr/lib/python3/dist-packages
/usr/lib/python3.7/dist-packages
/usr/lib/python3.8/site-packages
/home/<username>/.local/share/lib/python3.7/site-packages
/home/<username>/share/lib/python3.7/site-packages
and more
```
I am too lazy to type all the places an end user should check. 
I still feel that you should implement some other method to fix this issue, if you intend to release it to PYPI or have create a Github release. If it was only your personal project as mentioned in #7, you should rather not release it.
Hope you will find a method to fix it soon. you should consider reopening #7 related to this or add a `wont-fix` label to the issue, so I can stop bothering that issue, and try to implement some method for my PC instead

and its not anywhere here in Mac too. I will refernce mac in another issue

**Comment by kewbish** [comment]
Ah, alright. I'll probably add a link to a stackoverflow answer directing a user to more places they can look.

This project was always meant to be a personal project and I'd rather not complicate it so much with a launcher - personally, I'd rather people who didn't know try to email or open an issue then guide them from there. It doesn't really make sense to include a launcher when only two people who both know how to edit (that I know of) are using.

Regarding release - I was going to keep this just a GitHub project, but you suggested a release, and I think I'll follow through. Anyone who doesn't understand or has a problem can open an issue and contact me, or they're free to create a fork and develop off my model on their own. I'm not so worried about usability, rather just to get a project I can use (and if that benefits others, great! if not, I have other work, and I'll do my best to help, but I don't know if I can make so many requests happen). Just a thought - I don't plan on releasing for anyone besides developers. (will add this in the note!)

**Comment by srevinsaju** [comment]
Thanks
