### ISSUE TITLE
Fails on Mac

### ISSUE THREAD

**Issue by srevinsaju** [kewbish/Justin#13]
Umm, Where to edit the path to config?
![image](https://user-images.githubusercontent.com/48695438/77849190-6e8c9800-71d2-11ea-9d4a-e648bdf3ba3f.png)

As mentioned in the README.md, I wasn't able to find /usr/lib/..../ on Mac. I can find it out myself, but I am mentioning this to you as you would explore it by yourself. 

This is likely a case how it might be difficult for an end developer to change the code. Related to #7 again

**Comment by kewbish** [comment]
I'm not too concerned with this - though will add to README!
