### ISSUE TITLE
FileNotFoundError : config.jstn

### ISSUE THREAD

**Issue by srevinsaju** [kewbish/Justin#14]
```python
def jstn_command():
    path = r"path\to\config.jstn"
```

I have mentioned my path in the file. Unfortunately, Justin gives the error.
The same file with same path works on Windows, but not on Linux.
I have dropped the clue right here. Hope you will find out :laughing:

**Comment by kewbish** [comment]
I'm not sure what this means - I suspect it's to do with the slashes?

**Comment by srevinsaju** [comment]
Yes, its the forward slashes which is different in mac and linux. Use os.path.join() to create full paths

**Comment by kewbish** [comment]
Alright - that's probably a good practice. Apologies for not testing on Linux!
