### ISSUE TITLE
alias on Mac: bashrc not found 

### ISSUE THREAD

**Issue by srevinsaju** [kewbish/Justin#15]
> # :computer: Command Alias
> Alternatively, use DOSKEY (Windows) or alias (Linux / MacOS) to set up an alias to the justin\justin.py file.
> For example, doskey justin=python path\to\justin.py %* (on Windows, set up in target properties).
Information about these can be found for Windows and Linux / MacOS.

No .bashrc on MacOS Catalina 10.15, maybe you should add a spearate documentation link for MacOS catalina

> PS: If you want me to stop finding issues (some developers doesn't like issues / PRs) you can always tell me. Sorry if these are bugging you, just let me know XD

**Comment by kewbish** [comment]
Ah, I will definitely do that. I don't have a Mac either, so I'm not familiar with it and just thought to loop this in with Linux. Oops!

Regarding issues - I really appreciate the work you do, but I think the issues should *hopefully* decrease as I gradually slow development.

**Comment by srevinsaju** [comment]
I don't have a Mac either. as part of writing production software I have to keep multiple VMs ready. I thought this would help you


> Regarding issues - I really appreciate the work you do, but I think the issues should _hopefully_ decrease as I gradually slow development.

Good luck. hope it becomes a great project

**Comment by kewbish** [comment]
Ah - this isn't really a *production* piece, just a personal project, but thanks for picking that up!
> Good luck. hope it becomes a great project
Thanks - though I don't think the amt of users will increase anytime soon 😆

**Comment by srevinsaju** [comment]
Oops, I meant, I have to keep a MacOS VM because `I` write (production) software for multiple platforms. Just a correction

> Thanks - though I don't think the amt of users will increase anytime soon laughing

It will, I bet you

PS: I would have shared the project with other friends, but I thought one user (me) itself might be causing a lot of problems for you. Once these are fixed, sure, it will be

**Comment by kewbish** [comment]
> Oops, I meant, I have to keep a MacOS VM because I write (production) software for multiple platforms. Just a correction

Apologies for misinterpreting!

> It will, I bet you

🤞
