### ISSUE TITLE
No News on Output

### ISSUE THREAD

**Issue by srevinsaju** [kewbish/Justin#3]
https://asciinema.org/a/3axw1drtsCkzuMBRpBa7GoV47
Maybe you should try not releasing stable versions early.

**Comment by kewbish** [comment]
Works fine for me - do you have a NewsAPI key in your `config.jstn` file?

It should be under `[NewsApi]` like so:
```
[NewsApi]
Key = [keyyousignedfor]
```

**Comment by srevinsaju** [comment]
Yes

**Comment by kewbish** [comment]
Interesting, I'll look into that. However, it does seem to work on both of my test setups.

**Comment by kewbish** [comment]
It’s also possible that NewsAPI doesn’t have an endpoint for your country and isn’t returning any errors.

**Comment by srevinsaju** [comment]
Yup, thats the case. it should rather be an error which should be raise
