### ISSUE TITLE
Security Vulnerability of storing gmail password in config files

### ISSUE THREAD

**Issue by srevinsaju** [kewbish/Justin#5]
Configuration files are easily accessed by the system programs. It can be easily hacked off by a third part hacker. Rather, the app should use salted hash or a minimum AES crypto to hash the password in the config

**Comment by kewbish** [comment]
Good point, will add to backlog. Personally, I’m not very concerned about hackers targeting this, at least for now as user base remains small.

How would you go about implementing this?

**Comment by srevinsaju** [comment]
I would use an AES cipher to encrypt the gmail password. alternatively I will request System Password manager on linux, or a UAC-similar tkinter dialog to ask the user for the password.
