### ISSUE TITLE
Error on installation

### ISSUE THREAD

**Issue by srevinsaju** [kewbish/Justin#6]
Justin fails to install first time only on Linux
https://asciinema.org/a/JP5Y039CAEXh20FeMdqMpoSod

**Comment by kewbish** [comment]
Ah, I thought that would lead to errors.

Will look into an alternate fix.

Thanks for testing!

**Comment by srevinsaju** [comment]
Update: Installation fails almost every time. I was conflicting with my own personal justin 

Clean install caused package installation failures
