### ISSUE TITLE
Code is not to be edited by end user

### ISSUE THREAD

**Issue by srevinsaju** [kewbish/Justin#7]
The code is not to be expected to be edited by the end user.
On linux
```bash
sudo pip3 install https://github.com/kewbish/Justin/archive/master.zip
echo "ok" >> /usr/lib/python3.8/site-packages/Justin/justin.py
[permission denied]
```

**Comment by kewbish** [comment]
Is there a way to fix this from my end?

Wouldn't this work simply with `sudo`?

**Comment by srevinsaju** [comment]
Yes, but where can a developer know where the file is installed to unless he/she is a python developer.  I probably knew where to find the file after installing, so it was easier. might not be for a newbie developer.


> Is there a way to fix this from my end?

See how its done in [guiscrcpy](https://github.com/srevinsaju/guiscrcpy) and [sugaroid](https://github.com/srevinsaju/sugaroid)

**Comment by kewbish** [comment]
I can't seem to find where it's done - could you link directly?

On another note - thanks for debugging so many errors 😄, I don't use Linux often enough to see many of the bugs you've picked up.

**Comment by srevinsaju** [comment]
Welcome, but it doesn't work on my Windows VM too. 

In guiscrcpy its here: 

https://github.com/srevinsaju/guiscrcpy/blob/a907e87c8df3427dda854d0f1f4dd9ea87cf6894/guiscrcpy/launcher.py#L49

**Comment by kewbish** [comment]
Ack - I usually code for personal projects and don't really consider end-usability. 

Your implementation seems a little complex - I might just update the README with different installation instructions leading to a manual installation and alias.

Again, thanks for your help 😄
